from typing import Any, Iterator, Protocol, Self, Sequence


class BitVectorProtocol(Protocol):
    size: int
    filename: str | None
    more_to_read: bool

    def _setbit(self, posn: int | tuple[Any, ...] | Any, val: int | Any) -> None: ...
    def _getbit(self, pos: int | slice | Any) -> Any: ...
    def __xor__(self, other: Self) -> Self: ...
    def __and__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __add__(self, other: Self) -> Self: ...
    def __iadd__(self, other: Self) -> Self: ...
    def _getsize(self) -> int: ...
    def divide_into_two(self) -> list[Self]: ...
    def permute(self, permute_list: Sequence[int] | Any) -> Self: ...
    def unpermute(self, permute_list: Sequence[int] | Any) -> Self: ...
    def int_val(self) -> int: ...
    def get_bitvector_in_ascii(self) -> str: ...
    def get_bitvector_in_hex(self) -> str: ...
    def __lshift__(self, n: int) -> Self: ...
    def __rshift__(self, n: int) -> Self: ...
    def circular_rotate_left_by_one(self) -> None: ...
    def circular_rotate_right_by_one(self) -> None: ...
    def circular_rot_left(self) -> None: ...
    def circular_rot_right(self) -> None: ...
    def shift_left_by_one(self) -> None: ...
    def shift_right_by_one(self) -> None: ...
    def shift_left(self, n: int) -> Self: ...
    def shift_right(self, n: int) -> Self: ...
    def __getitem__(self, pos: int | slice | Any) -> Any: ...
    def __setitem__(self, pos: int | slice | Any, item: int | Self | Any) -> Any: ...
    def __len__(self) -> int: ...
    def __int__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __deepcopy__(self, memo: dict[int, Any] | None = None) -> Self: ...
    def _resize_pad_from_left(self, n: int) -> Self: ...
    def pad_from_left(self, n: int) -> None: ...
    def pad_from_right(self, n: int) -> None: ...
    def __contains__(self, otherBitVec: Self) -> bool: ...
    def reset(self, val: int | Any) -> Self: ...
    def count_bits(self) -> int: ...
    def set_value(
        self,
        *,
        filename: str | None = None,
        fp: Any = None,
        size: int | None = None,
        intVal: int | None = None,
        bitlist: Any = None,
        bitstring: str | None = None,
        hexstring: str | None = None,
        textstring: str | None = None,
        rawbytes: bytes | None = None,
    ) -> None: ...
    def count_bits_sparse(self) -> int: ...
    def next_set_bit(self, from_index: int = 0) -> int: ...
    def rank_of_bit_set_at_index(self, position: int) -> int: ...
    def is_power_of_2(self) -> bool: ...
    def is_power_of_2_sparse(self) -> bool: ...
    def reverse(self) -> Self: ...
    def length(self) -> int: ...
    def runs(self) -> list[str]: ...
    def gen_random_bits(self, width: int) -> Self: ...
    def min_canonical(self) -> Self: ...
